# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b82877dd3c6cc04deac3b24c3f23d763"
name = "bulk-order"
handle = "bulk-order-20"
application_url = "https://supporters-vacuum-sie-vacancies.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"


  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app-subscription-update"
  
  [app_proxy]
  url = "/app/app-proxy-plan"
  subpath = "bulk-order"
  prefix = "apps"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_app_proxy"

[auth]
redirect_urls = [
  "https://supporters-vacuum-sie-vacancies.trycloudflare.com",
  "https://supporters-vacuum-sie-vacancies.trycloudflare.com/auth/shopify/callback",
  "https://supporters-vacuum-sie-vacancies.trycloudflare.com/auth/callback",]

[pos]
embedded = false
